---
# tasks file for ansible-airflow

- name: Load a variable files
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "empty.yml"
  tags: [always]

- import_tasks: install.yml
  tags: [airflow, airflow_install]

- import_tasks: configure.yml
  tags: [airflow, airflow_configure]

- import_tasks: service.yml
  tags: [airflow, airflow_service]
